version: 0.0
Resources:
  - TargetService:
      Type: AWS:ECS:Service
      Properties:
        # <TASK_DEFINITION> will be replaced by codedeploy when the pipeline runs
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "backend-app" # must be same container_name in service - task
          ContainerPort: 8088